spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDB_CONNECTION_STRING}
    username: ${RDB_USER}
    password: ${RDB_PASSWORD}
  mail:
    host: smtp.naver.com
    port: 465
    username: dbswlsdyd730@naver.com
    password: ${JINYONG_NAVER_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    database: mysql

  data:
    redis:
      host: ${CACHE_HOST}
      port: ${CACHE_PORT}
      password: ${CACHE_PASSWORD}
      jedis:
        pool:
          max-wait:
    mongodb:
      database: ${DDB_NAME}
      host: ${DDB_HOST}
      port: ${DDB_PORT}
      username: ${DDB_USER}
      password: ${DDB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiry-in-seconds: ${JWT_EXPIRY_IN_SECONDS}